package signin;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Duong
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        deleteusercardButton1 = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        hoivien = new javax.swing.JButton();
        thehoivien = new javax.swing.JButton();
        thoigiantap = new javax.swing.JButton();
        nhanvien = new javax.swing.JButton();
        thongke = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        framehoivien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        username1 = new javax.swing.JLabel();
        useridcard1 = new javax.swing.JLabel();
        userphone1 = new javax.swing.JLabel();
        useraddress1 = new javax.swing.JLabel();
        registertime1 = new javax.swing.JLabel();
        usertimeTextfield1 = new javax.swing.JTextField();
        useraddressTextfield1 = new javax.swing.JTextField();
        userphoneTextfield1 = new javax.swing.JTextField();
        useridcardTextfield1 = new javax.swing.JTextField();
        usernameTextfield1 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        useraddUserButton = new javax.swing.JButton();
        userdeleteButton = new javax.swing.JButton();
        usereditButton = new javax.swing.JButton();
        framethehoivien = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cardendday = new javax.swing.JTextField();
        endday = new javax.swing.JLabel();
        beginday = new javax.swing.JLabel();
        cardbeginday = new javax.swing.JTextField();
        usercardlevel = new javax.swing.JLabel();
        cardlevelbox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cardphoneTextfield = new javax.swing.JTextField();
        usernamecard = new javax.swing.JLabel();
        cardnameTextfield = new javax.swing.JTextField();
        idcard = new javax.swing.JLabel();
        idcardTextfield = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        addusercardButton = new javax.swing.JButton();
        deleteusercardButton = new javax.swing.JButton();
        deleteusercardButton2 = new javax.swing.JButton();
        framethoigiantap = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        timeTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        timeidcard = new javax.swing.JLabel();
        timeidcardTextlield = new javax.swing.JTextField();
        timenametxt = new javax.swing.JTextField();
        timename = new javax.swing.JLabel();
        timeusercardlevel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        timebegintime = new javax.swing.JTextField();
        begintime = new javax.swing.JLabel();
        endtime = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        usereditButton1 = new javax.swing.JButton();
        userdeleteButton1 = new javax.swing.JButton();
        framenhanvien = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        emplid = new javax.swing.JLabel();
        emplname = new javax.swing.JLabel();
        emplphone = new javax.swing.JLabel();
        empladdress = new javax.swing.JLabel();
        emplworktime = new javax.swing.JLabel();
        emplworktimeBox = new javax.swing.JComboBox<>();
        empladdressTextfiled = new javax.swing.JTextField();
        emplphoneTextfield = new javax.swing.JTextField();
        emplnameTextfield = new javax.swing.JTextField();
        emplidTextfield = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        empladdButton = new javax.swing.JButton();
        empleditButton = new javax.swing.JButton();
        empldeleteButton = new javax.swing.JButton();
        framethongke = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();

        jTable1.setForeground(new java.awt.Color(255, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ Tên ", "Mã Thẻ Hội Viên", "Số Điện Thoại", "Địa Chỉ", "Ngày Đăng Ký Thẻ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionForeground(new java.awt.Color(0, 120, 170));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setForeground(new java.awt.Color(255, 51, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ Tên ", "Mã Thẻ Hội Viên", "Số Điện Thoại", "Địa Chỉ", "Ngày Đăng Ký Thẻ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setSelectionForeground(new java.awt.Color(0, 120, 170));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 160));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thẻ Hội Viên", "Họ Tên", "Số Điện Thoại", "Loại Thẻ Hội Viên", "Ngày Đăng Ký", "Ngày Hết Hạn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setPreferredSize(new java.awt.Dimension(300, 160));
        jScrollPane3.setViewportView(jTable3);

        deleteusercardButton1.setBackground(new java.awt.Color(60, 72, 107));
        deleteusercardButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteusercardButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteusercardButton1.setText("Xóa Thẻ Hội Viên");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lí Phòng Gym");

        menu.setPreferredSize(new java.awt.Dimension(200, 492));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hoivien.setBackground(new java.awt.Color(185, 243, 252));
        hoivien.setFont(new java.awt.Font("SVN-Russell", 0, 14)); // NOI18N
        hoivien.setText("Thông Tin Hội Viên");
        hoivien.setPreferredSize(new java.awt.Dimension(159, 30));
        hoivien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoivienMouseClicked(evt);
            }
        });
        hoivien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoivienActionPerformed(evt);
            }
        });
        menu.add(hoivien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 46));

        thehoivien.setBackground(new java.awt.Color(185, 243, 252));
        thehoivien.setFont(new java.awt.Font("SVN-Russell", 0, 14)); // NOI18N
        thehoivien.setText("Thẻ Hội Viên");
        thehoivien.setToolTipText("");
        thehoivien.setMaximumSize(new java.awt.Dimension(159, 24));
        thehoivien.setMinimumSize(new java.awt.Dimension(159, 24));
        thehoivien.setPreferredSize(new java.awt.Dimension(159, 30));
        thehoivien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thehoivienMouseClicked(evt);
            }
        });
        thehoivien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thehoivienActionPerformed(evt);
            }
        });
        menu.add(thehoivien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 46));

        thoigiantap.setBackground(new java.awt.Color(185, 243, 252));
        thoigiantap.setFont(new java.awt.Font("SVN-Russell", 0, 14)); // NOI18N
        thoigiantap.setText("Quản Lý Thời Gian Tập");
        thoigiantap.setMaximumSize(new java.awt.Dimension(159, 24));
        thoigiantap.setMinimumSize(new java.awt.Dimension(159, 24));
        thoigiantap.setPreferredSize(new java.awt.Dimension(159, 30));
        thoigiantap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoigiantapMouseClicked(evt);
            }
        });
        thoigiantap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoigiantapActionPerformed(evt);
            }
        });
        menu.add(thoigiantap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 46));

        nhanvien.setBackground(new java.awt.Color(185, 243, 252));
        nhanvien.setFont(new java.awt.Font("SVN-Russell", 0, 14)); // NOI18N
        nhanvien.setText("Quản Lý Nhân Viên");
        nhanvien.setMaximumSize(new java.awt.Dimension(159, 24));
        nhanvien.setMinimumSize(new java.awt.Dimension(159, 24));
        nhanvien.setPreferredSize(new java.awt.Dimension(159, 30));
        nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanvienMouseClicked(evt);
            }
        });
        nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanvienActionPerformed(evt);
            }
        });
        menu.add(nhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 46));

        thongke.setBackground(new java.awt.Color(185, 243, 252));
        thongke.setFont(new java.awt.Font("SVN-Russell", 0, 14)); // NOI18N
        thongke.setText("Báo Cáo Thống Kê");
        thongke.setMaximumSize(new java.awt.Dimension(159, 24));
        thongke.setMinimumSize(new java.awt.Dimension(159, 24));
        thongke.setPreferredSize(new java.awt.Dimension(159, 30));
        thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongkeMouseClicked(evt);
            }
        });
        menu.add(thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 46));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fitness.png"))); // NOI18N
        menu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(174, 226, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        framehoivien.setBackground(new java.awt.Color(174, 226, 255));

        jLabel2.setFont(new java.awt.Font("SVN-Russell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jLabel2.setText("THÔNG TIN HỘI VIÊN");

        jPanel15.setBackground(new java.awt.Color(174, 226, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable4.setForeground(new java.awt.Color(255, 51, 51));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Họ Tên ", "Mã Thẻ Hội Viên", "Số Điện Thoại", "Địa Chỉ", "Ngày Đăng Ký Thẻ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setSelectionForeground(new java.awt.Color(0, 120, 170));
        jScrollPane4.setViewportView(jTable4);

        jPanel16.setBackground(new java.awt.Color(174, 226, 255));

        username1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        username1.setForeground(new java.awt.Color(60, 72, 107));
        username1.setText("Họ Tên");

        useridcard1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        useridcard1.setForeground(new java.awt.Color(60, 72, 107));
        useridcard1.setText("Mã Thẻ Hội Viên");

        userphone1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userphone1.setForeground(new java.awt.Color(60, 72, 107));
        userphone1.setText("Số Điện Thoại");

        useraddress1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        useraddress1.setForeground(new java.awt.Color(60, 72, 107));
        useraddress1.setText("Địa Chỉ");

        registertime1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registertime1.setForeground(new java.awt.Color(60, 72, 107));
        registertime1.setText("Ngày ĐK Thẻ");

        useraddressTextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useraddressTextfield1ActionPerformed(evt);
            }
        });

        usernameTextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextfield1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userphone1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useraddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registertime1)
                    .addComponent(useridcard1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTextfield1)
                    .addComponent(useridcardTextfield1)
                    .addComponent(usertimeTextfield1)
                    .addComponent(userphoneTextfield1)
                    .addComponent(useraddressTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username1)
                    .addComponent(usernameTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useridcard1)
                    .addComponent(useridcardTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userphoneTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userphone1))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useraddressTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useraddress1))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registertime1)
                    .addComponent(usertimeTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(174, 226, 255));

        useraddUserButton.setBackground(new java.awt.Color(60, 72, 107));
        useraddUserButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        useraddUserButton.setForeground(new java.awt.Color(255, 255, 255));
        useraddUserButton.setText("Thêm Hội Viên");
        useraddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useraddUserButtonActionPerformed(evt);
            }
        });

        userdeleteButton.setBackground(new java.awt.Color(60, 72, 107));
        userdeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userdeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        userdeleteButton.setText("Xóa");

        usereditButton.setBackground(new java.awt.Color(60, 72, 107));
        usereditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usereditButton.setForeground(new java.awt.Color(255, 255, 255));
        usereditButton.setText("Sửa ");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(useraddUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usereditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userdeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(useraddUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(usereditButton)
                .addGap(18, 18, 18)
                .addComponent(userdeleteButton)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout framehoivienLayout = new javax.swing.GroupLayout(framehoivien);
        framehoivien.setLayout(framehoivienLayout);
        framehoivienLayout.setHorizontalGroup(
            framehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framehoivienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(framehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4))
                    .addGroup(framehoivienLayout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        framehoivienLayout.setVerticalGroup(
            framehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framehoivienLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(framehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(framehoivien, "card2");

        framethehoivien.setBackground(new java.awt.Color(174, 226, 255));

        jPanel18.setBackground(new java.awt.Color(174, 226, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("SVN-Russell", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id-card.png"))); // NOI18N
        jLabel11.setText("THẺ HỘI VIÊN");

        jScrollPane5.setPreferredSize(new java.awt.Dimension(300, 160));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thẻ Hội Viên", "Họ Tên", "Số Điện Thoại", "Loại Thẻ Hội Viên", "Ngày Đăng Ký", "Ngày Hết Hạn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.setPreferredSize(new java.awt.Dimension(300, 160));
        jScrollPane5.setViewportView(jTable5);

        jPanel1.setBackground(new java.awt.Color(174, 226, 255));

        endday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        endday.setForeground(new java.awt.Color(60, 72, 107));
        endday.setText("Ngày Kết Thúc");

        beginday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        beginday.setForeground(new java.awt.Color(60, 72, 107));
        beginday.setText("Ngày ĐK Thẻ");

        cardbeginday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardbegindayActionPerformed(evt);
            }
        });

        usercardlevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usercardlevel.setForeground(new java.awt.Color(60, 72, 107));
        usercardlevel.setText("Loại Thẻ Hội Viên");

        cardlevelbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cardlevelbox.setForeground(new java.awt.Color(60, 72, 107));
        cardlevelbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thẻ Buổi", "Thẻ Tháng", "Thẻ Năm", "Thẻ VIP", " ", " " }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(60, 72, 107));
        jLabel12.setText("Số Điện Thoại");

        usernamecard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernamecard.setForeground(new java.awt.Color(60, 72, 107));
        usernamecard.setText("Họ Tên");

        cardnameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnameTextfieldActionPerformed(evt);
            }
        });

        idcard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idcard.setForeground(new java.awt.Color(60, 72, 107));
        idcard.setText("Mã Thẻ Hội Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usercardlevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernamecard, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beginday)
                            .addComponent(endday)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(idcard))
                    .addGap(41, 41, 41)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cardlevelbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardnameTextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cardphoneTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(idcardTextfield)
                        .addComponent(cardbeginday)
                        .addComponent(cardendday))
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(idcard)
                        .addComponent(idcardTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(usernamecard)
                        .addComponent(cardnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel12)
                        .addComponent(cardphoneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(usercardlevel)
                        .addComponent(cardlevelbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(beginday)
                        .addComponent(cardbeginday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(endday)
                        .addComponent(cardendday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(174, 226, 255));

        addusercardButton.setBackground(new java.awt.Color(60, 72, 107));
        addusercardButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addusercardButton.setForeground(new java.awt.Color(255, 255, 255));
        addusercardButton.setText("Tạo Thẻ Hội Viên");
        addusercardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusercardButtonActionPerformed(evt);
            }
        });

        deleteusercardButton.setBackground(new java.awt.Color(60, 72, 107));
        deleteusercardButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteusercardButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteusercardButton.setText("Xóa");

        deleteusercardButton2.setBackground(new java.awt.Color(60, 72, 107));
        deleteusercardButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteusercardButton2.setForeground(new java.awt.Color(255, 255, 255));
        deleteusercardButton2.setText("Sửa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addusercardButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteusercardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteusercardButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addusercardButton)
                .addGap(27, 27, 27)
                .addComponent(deleteusercardButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(deleteusercardButton))
        );

        javax.swing.GroupLayout framethehoivienLayout = new javax.swing.GroupLayout(framethehoivien);
        framethehoivien.setLayout(framethehoivienLayout);
        framethehoivienLayout.setHorizontalGroup(
            framethehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framethehoivienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(framethehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framethehoivienLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(framethehoivienLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framethehoivienLayout.createSequentialGroup()
                        .addGroup(framethehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        framethehoivienLayout.setVerticalGroup(
            framethehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framethehoivienLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(framethehoivienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framethehoivienLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(framethehoivienLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(99, Short.MAX_VALUE))))
        );

        jPanel2.add(framethehoivien, "card3");

        framethoigiantap.setBackground(new java.awt.Color(174, 226, 255));
        framethoigiantap.setPreferredSize(new java.awt.Dimension(813, 545));

        jLabel13.setFont(new java.awt.Font("SVN-Russell", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hourglass (1).png"))); // NOI18N
        jLabel13.setText("QUẢN LÍ THỜI GIAN TẬP");

        jPanel19.setBackground(new java.awt.Color(174, 226, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        timeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Thẻ Hội Viên", "Họ Tên", "Loại Thẻ Hội Viên", "Thời Gian Đến", "Thời Gian Đi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(timeTable);

        jPanel5.setBackground(new java.awt.Color(174, 226, 255));

        timeidcard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeidcard.setForeground(new java.awt.Color(60, 72, 107));
        timeidcard.setText("Mã Thẻ Hội Viên");

        timeidcardTextlield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeidcardTextlieldActionPerformed(evt);
            }
        });

        timenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timenametxtActionPerformed(evt);
            }
        });

        timename.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timename.setForeground(new java.awt.Color(60, 72, 107));
        timename.setText("Họ Tên");

        timeusercardlevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        timeusercardlevel.setForeground(new java.awt.Color(60, 72, 107));
        timeusercardlevel.setText("Loại Thẻ Hội Viên");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thẻ Buổi", "Thẻ Tháng", "Thẻ Năm", "Thẻ VIP", " ", " " }));

        begintime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        begintime.setForeground(new java.awt.Color(60, 72, 107));
        begintime.setText("Thời Gian Đến");

        endtime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        endtime.setForeground(new java.awt.Color(60, 72, 107));
        endtime.setText("Thời Gian Đi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endtime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(begintime)
                        .addComponent(timeusercardlevel)
                        .addComponent(timename, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeidcard)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 223, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(timebegintime)
                            .addComponent(timenametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeidcardTextlield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeidcardTextlield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeidcard))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timename)
                    .addComponent(timenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeusercardlevel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(begintime)
                    .addComponent(timebegintime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endtime)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(174, 226, 255));

        usereditButton1.setBackground(new java.awt.Color(60, 72, 107));
        usereditButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usereditButton1.setForeground(new java.awt.Color(255, 255, 255));
        usereditButton1.setText("Sửa ");

        userdeleteButton1.setBackground(new java.awt.Color(60, 72, 107));
        userdeleteButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userdeleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        userdeleteButton1.setText("Xóa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usereditButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userdeleteButton1))
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(usereditButton1)
                .addGap(18, 18, 18)
                .addComponent(userdeleteButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout framethoigiantapLayout = new javax.swing.GroupLayout(framethoigiantap);
        framethoigiantap.setLayout(framethoigiantapLayout);
        framethoigiantapLayout.setHorizontalGroup(
            framethoigiantapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framethoigiantapLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(framethoigiantapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(framethoigiantapLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        framethoigiantapLayout.setVerticalGroup(
            framethoigiantapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framethoigiantapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(framethoigiantapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framethoigiantapLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, framethoigiantapLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );

        jPanel2.add(framethoigiantap, "card4");

        framenhanvien.setBackground(new java.awt.Color(174, 226, 255));

        jLabel15.setFont(new java.awt.Font("SVN-Russell", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/teamwork.png"))); // NOI18N
        jLabel15.setText("QUẢN LÍ NHÂN VIÊN");

        jPanel20.setBackground(new java.awt.Color(174, 226, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "Số Điện Thoại", "Địa Chỉ", "Ca Làm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable6);

        jPanel7.setBackground(new java.awt.Color(174, 226, 255));

        emplid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emplid.setForeground(new java.awt.Color(60, 72, 107));
        emplid.setText("Mã Nhân Viên");

        emplname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emplname.setForeground(new java.awt.Color(60, 72, 107));
        emplname.setText("Họ Tên");

        emplphone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emplphone.setForeground(new java.awt.Color(60, 72, 107));
        emplphone.setText("Số Điện Thoại");

        empladdress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empladdress.setForeground(new java.awt.Color(60, 72, 107));
        empladdress.setText("Địa Chỉ");

        emplworktime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emplworktime.setForeground(new java.awt.Color(60, 72, 107));
        emplworktime.setText("Ca Làm");

        emplworktimeBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emplworktimeBox.setForeground(new java.awt.Color(60, 72, 107));
        emplworktimeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Chiều", "Tối" }));

        empladdressTextfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empladdressTextfiledActionPerformed(evt);
            }
        });

        emplidTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emplidTextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emplphone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(empladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emplworktime))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emplphoneTextfield)
                                    .addComponent(empladdressTextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(emplworktimeBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emplid, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emplname))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emplnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emplidTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emplidTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emplid))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emplnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emplname))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emplphoneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emplphone))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empladdressTextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(empladdress))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emplworktime)
                        .addComponent(emplworktimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel21.setBackground(new java.awt.Color(174, 226, 255));

        empladdButton.setBackground(new java.awt.Color(60, 72, 107));
        empladdButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empladdButton.setForeground(new java.awt.Color(255, 255, 255));
        empladdButton.setText("Thêm Nhân Viên");
        empladdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empladdButtonActionPerformed(evt);
            }
        });

        empleditButton.setBackground(new java.awt.Color(60, 72, 107));
        empleditButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empleditButton.setForeground(new java.awt.Color(255, 255, 255));
        empleditButton.setText("Sửa");

        empldeleteButton.setBackground(new java.awt.Color(60, 72, 107));
        empldeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empldeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        empldeleteButton.setText("Xóa");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empladdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empleditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empldeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(empladdButton)
                .addGap(18, 18, 18)
                .addComponent(empleditButton)
                .addGap(17, 17, 17)
                .addComponent(empldeleteButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout framenhanvienLayout = new javax.swing.GroupLayout(framenhanvien);
        framenhanvien.setLayout(framenhanvienLayout);
        framenhanvienLayout.setHorizontalGroup(
            framenhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framenhanvienLayout.createSequentialGroup()
                .addGroup(framenhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framenhanvienLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(framenhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(framenhanvienLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        framenhanvienLayout.setVerticalGroup(
            framenhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framenhanvienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(framenhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(framenhanvien, "card5");

        framethongke.setBackground(new java.awt.Color(174, 226, 255));

        jLabel17.setFont(new java.awt.Font("SVN-Russell", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/business-report.png"))); // NOI18N
        jLabel17.setText("BÁO CÁO THỐNG KÊ");

        jPanel22.setBackground(new java.awt.Color(174, 226, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ngày", "Khung Giờ", "Số Người Tập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        javax.swing.GroupLayout framethongkeLayout = new javax.swing.GroupLayout(framethongke);
        framethongke.setLayout(framethongkeLayout);
        framethongkeLayout.setHorizontalGroup(
            framethongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framethongkeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(framethongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(framethongkeLayout.createSequentialGroup()
                        .addGroup(framethongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        framethongkeLayout.setVerticalGroup(
            framethongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framethongkeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(framethongke, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoivienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoivienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoivienActionPerformed

    private void thehoivienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thehoivienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thehoivienActionPerformed

    private void thoigiantapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoigiantapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thoigiantapActionPerformed

    private void nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhanvienActionPerformed

    private void hoivienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoivienMouseClicked
       framehoivien.setVisible(true);
       framethehoivien.setVisible(false);
       framethoigiantap.setVisible(false);
       framenhanvien.setVisible(false);
       framethongke.setVisible(false);
    }//GEN-LAST:event_hoivienMouseClicked

    private void thehoivienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thehoivienMouseClicked
     framehoivien.setVisible(false);
       framethehoivien.setVisible(true);
       framethoigiantap.setVisible(false);
       framenhanvien.setVisible(false);
       framethongke.setVisible(false);
    }//GEN-LAST:event_thehoivienMouseClicked

    private void useraddressTextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useraddressTextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useraddressTextfield1ActionPerformed

    private void usernameTextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextfield1ActionPerformed

    private void useraddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useraddUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useraddUserButtonActionPerformed

    private void cardbegindayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardbegindayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardbegindayActionPerformed

    private void cardnameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnameTextfieldActionPerformed

    private void addusercardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusercardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addusercardButtonActionPerformed

    private void timeidcardTextlieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeidcardTextlieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeidcardTextlieldActionPerformed

    private void timenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timenametxtActionPerformed

    private void empladdressTextfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empladdressTextfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empladdressTextfiledActionPerformed

    private void emplidTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emplidTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emplidTextfieldActionPerformed

    private void empladdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empladdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empladdButtonActionPerformed

    private void thoigiantapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoigiantapMouseClicked
        // TODO add your handling code here:
         framehoivien.setVisible(false);
       framethehoivien.setVisible(false);
       framethoigiantap.setVisible(true);
       framenhanvien.setVisible(false);
       framethongke.setVisible(false);
    }//GEN-LAST:event_thoigiantapMouseClicked

    private void nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanvienMouseClicked
        // TODO add your handling code here:
         framehoivien.setVisible(false);
       framethehoivien.setVisible(false);
       framethoigiantap.setVisible(false);
       framenhanvien.setVisible(true);
       framethongke.setVisible(false);
    }//GEN-LAST:event_nhanvienMouseClicked

    private void thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeMouseClicked
        // TODO add your handling code here:
         framehoivien.setVisible(false);
       framethehoivien.setVisible(false);
       framethoigiantap.setVisible(false);
       framenhanvien.setVisible(false);
       framethongke.setVisible(true);
    }//GEN-LAST:event_thongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addusercardButton;
    private javax.swing.JLabel beginday;
    private javax.swing.JLabel begintime;
    private javax.swing.JTextField cardbeginday;
    private javax.swing.JTextField cardendday;
    private javax.swing.JComboBox<String> cardlevelbox;
    private javax.swing.JTextField cardnameTextfield;
    private javax.swing.JTextField cardphoneTextfield;
    private javax.swing.JButton deleteusercardButton;
    private javax.swing.JButton deleteusercardButton1;
    private javax.swing.JButton deleteusercardButton2;
    private javax.swing.JButton empladdButton;
    private javax.swing.JLabel empladdress;
    private javax.swing.JTextField empladdressTextfiled;
    private javax.swing.JButton empldeleteButton;
    private javax.swing.JButton empleditButton;
    private javax.swing.JLabel emplid;
    private javax.swing.JTextField emplidTextfield;
    private javax.swing.JLabel emplname;
    private javax.swing.JTextField emplnameTextfield;
    private javax.swing.JLabel emplphone;
    private javax.swing.JTextField emplphoneTextfield;
    private javax.swing.JLabel emplworktime;
    private javax.swing.JComboBox<String> emplworktimeBox;
    private javax.swing.JLabel endday;
    private javax.swing.JLabel endtime;
    private javax.swing.JPanel framehoivien;
    private javax.swing.JPanel framenhanvien;
    private javax.swing.JPanel framethehoivien;
    private javax.swing.JPanel framethoigiantap;
    private javax.swing.JPanel framethongke;
    private javax.swing.JButton hoivien;
    private javax.swing.JLabel idcard;
    private javax.swing.JTextField idcardTextfield;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel menu;
    private javax.swing.JButton nhanvien;
    private javax.swing.JLabel registertime1;
    private javax.swing.JButton thehoivien;
    private javax.swing.JButton thoigiantap;
    private javax.swing.JButton thongke;
    private javax.swing.JTable timeTable;
    private javax.swing.JTextField timebegintime;
    private javax.swing.JLabel timeidcard;
    private javax.swing.JTextField timeidcardTextlield;
    private javax.swing.JLabel timename;
    private javax.swing.JTextField timenametxt;
    private javax.swing.JLabel timeusercardlevel;
    private javax.swing.JButton useraddUserButton;
    private javax.swing.JLabel useraddress1;
    private javax.swing.JTextField useraddressTextfield1;
    private javax.swing.JLabel usercardlevel;
    private javax.swing.JButton userdeleteButton;
    private javax.swing.JButton userdeleteButton1;
    private javax.swing.JButton usereditButton;
    private javax.swing.JButton usereditButton1;
    private javax.swing.JLabel useridcard1;
    private javax.swing.JTextField useridcardTextfield1;
    private javax.swing.JLabel username1;
    private javax.swing.JTextField usernameTextfield1;
    private javax.swing.JLabel usernamecard;
    private javax.swing.JLabel userphone1;
    private javax.swing.JTextField userphoneTextfield1;
    private javax.swing.JTextField usertimeTextfield1;
    // End of variables declaration//GEN-END:variables
}
